# Generated by Django 5.2.6 on 2025-10-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Student Name', max_length=255)),
                ('ref_no', models.CharField(help_text='Reference Number', max_length=50, unique=True)),
                ('department', models.CharField(help_text='Department (e.g., CSE, ECE, MECH)', max_length=100)),
                ('year', models.IntegerField(help_text='Year of Study (e.g., 1, 2, 3, 4)')),
                ('email', models.EmailField(help_text='Email Address', max_length=254)),
                ('dob', models.DateField(help_text='Date of Birth')),
            ],
        ),
    ]
