# Generated by Django 5.2.6 on 2025-10-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Car Name', max_length=255)),
                ('model', models.CharField(help_text='model', max_length=50, unique=True)),
                ('color', models.CharField(help_text='Color (e.g., black , white , blue , green)', max_length=100)),
                ('manufacturing_date', models.DateField()),
                ('Horse_power', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
